name: onlyNPM

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup-node
      if: steps.npmCache.outputd.cache-hit != 'true'
      uses: actions/setup-node@v3
      id: npmCache
      with:
         node-version: 18
         cache: 'npm'

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run test
        run: npm test
